blank_issues_enabled: false
contact_links:
  - name: âœï¸ Discussion Posts
    url: https://github.com/ejektaflex/Bountiful/discussions
    about: Not a bug? Got an idea or mod compat request? Put it here!
  - name: ğŸ˜Š Discord
    url: https://discord.gg/BaH88W9
    about: Want to talk with me directly? You can find us here!
